### PR TITLE
Adapt sf2dlib to use citro3d under the hood

### PR DESCRIPTION
**Pull request by fincs**
As discussed on IRC, here are my changes to make sf2dlib work with citro3d instead of the old and deprecated libctru GPU API (which was recently removed in upstream libctru). This PR is still kind of incomplete so it would be nice to have sf2dlib users test these changes with their programs in order to ensure sf2dlib continues to function properly.

Changes:
- Added sf2d_set_transform for specifying a custom transformation matrix that is used to convert input vertices directly in the vertex shader
- Updated Makefiles to the latest devkitARM standard
- sf2d_private was removed because citro3d already has math functions
- SF2D_PLACE_TEMP was removed as there is no equivalent on citro3d
- sf2d_bind_texture_parameters was removed for the same reason
- sf2d_draw_quad_uv's last parameter was removed because it depends on sf2d_bind_texture_parameters

### CODE REVIEW

**Comment by xerpi** [comment]
Awesome job you did there, I'll merge it once we get some positive feedback. Maybe it's a good opportunity to merge sfil (https://github.com/xerpi/sfillib) since it really doesn't make much sense to have these two libs separated.

**Comment by JerwuQu** [comment]
This looks great! Nice work!

Edit: Works on my machine:tm:

**Comment by Bryce-Dixon** [comment]
So much this please.

**Comment by Rinnegatamante** [comment]
I'm going to test such modifications in next week in lpp-3ds and i'l report back any issue i find. Awesome job, that's something hardly requested by a lot of devs.

**Comment by xerpi** [comment]
OK I'll merge it, let's hope everybody works fine.

**Comment by kitlith** [comment]
This is now using cirto3d, so the README should be updated?

**Pull request merged**
