### PR TITLE
quick fix, crash after too many calls

### PR DESCRIPTION
**Pull request by Lectem**
I added a pointer check for each sf2d_draw_\* function so that app doesnt crash but stop drawing instead.

I don't understand why you would use a pool if it's not to draw it all at once though...

### CODE REVIEW

**Comment by xerpi** [comment]
Good one, basically I use a temporary memory pool to allocate vertices because maybe you only want to draw a rectangle on one frame, and not on the next, so I use this fast pool (mallocing on that pool is just moving an offset) to be able to do that without overhead, and then I set the offset to 0 at the start of each frame.
Btw I think:

``` c
if (!vertices) return;
```

Would be better (if you don't mind).

**Comment by Lectem** [comment]
I still think that it is more or less useless. I mean, having a simple pool of union of sf2d_vertex_pos_tex and sf2d_vertex_pos_col would suffice for this, the only problem would be if GPU_DrawArray(GPU_TRIANGLE_STRIP, 4); was asynch and that we changed values too fast

**Comment by Lectem** [comment]
If you really need a pool, make it a cyclic one, if you reach the end, reset it so that we can still draw stuff

**Comment by xerpi** [comment]
The problem is that the GPU_DrawArray simply adds a command to the GPU command queue, so we must not delete the vertices until we call:

``` c
    GPU_FinishDrawing();
    GPUCMD_Finalize();
    GPUCMD_FlushAndRun(NULL);
```

**Comment by Lectem** [comment]
I wonder if we couldn't simply do

```
GPUCMD_FlushAndRun(NULL);
gspWaitForP3D();
GPUCMD_SetBufferOffset(0);
```

or

```
GPUCMD_Run(NULL);
gspWaitForP3D();
GPUCMD_SetBufferOffset(0);
```

so that the the cmd buffer would be treated and just continue issuing new commands.
Anyway, I think you could close the pull request as this subject is another issue

**Comment by xerpi** [comment]
Right, closed.

**Pull request merged**
